---
host: https://user-guide.data-platform.service.justice.gov.uk
show_govuk_logo: false
service_name: Data platform User Guide
service_link: /
header_links:
enable_search: true
collapsible_nav: true
max_toc_heading_level: 3
prevent_indexing: true
show_contribution_banner: true
github_repo: ministryofjustice/data-platform-user-guide
github_branch: main
full_service_name: Data platform User Guide
show_expiry: true
show_review_banner: true
